### ISSUE TITLE
Add feature for current Speeds and current Up/Downloading Torrents count

### ISSUE THREAD

**Issue by r-netizen** [thde/rtorrent_exporter#52]
Hi,

i would love to geta  feature that shows the count of currently uploading/downloading torrents and also the current Down/Upload Speeds.
Are you already planning on something like this?
If i find some free time (and my go skills are sufficient) i might take a look into this as well :)

**Comment by thde** [comment]
Should be possible:
* https://pkg.go.dev/github.com/mrobinsn/go-rtorrent/rtorrent#RTorrent.DownRate
* https://pkg.go.dev/github.com/mrobinsn/go-rtorrent/rtorrent#RTorrent.UpRate

**Comment by thde** [comment]
Trying to stay in line with having the most raw metrics in Prometheus, I think the route of aggregating the rate by using the `rate()` function, should be the way to go.
