### ISSUE TITLE
BUG: "stopped": rtorrent.ViewStopped 

### ISSUE THREAD

**Issue by ac1dburnz** [thde/rtorrent_exporter#62]
"stopped": rtorrent.ViewStopped and hashing No longer works since update 1.3.0

**Comment by thde** [comment]
I can't replicate this:
```
exporter-scraper-1  | # HELP rtorrent_torrents_total Torrent count by view.
exporter-scraper-1  | # TYPE rtorrent_torrents_total counter
exporter-scraper-1  | rtorrent_torrents_total{label="",view="main"} 1
exporter-scraper-1  | rtorrent_torrents_total{label="",view="stopped"} 1
```
But maybe you're expecting it to report 0 if no torrent can be found in the view?
https://github.com/thde/rtorrent_exporter/commit/5b8eccb5038e443ca177c1e5877f97894097858b

**Comment by ac1dburnz** [comment]
ya most likey, thanks dude
