### ISSUE TITLE
FeatureRequest: More information about the files specifically

### ISSUE THREAD

**Issue by ac1dburnz** [thde/rtorrent_exporter#63]
If possible, i would like to more inform information about the downloads. I want to be able to track how much rtorrent_uploaded_bytes and rtorrent_downloaded_bytes broken down into each tracker. I want to be able to track the usage per tracker

**Comment by thde** [comment]
I wanted to do the same ;) If you label your torrents, you can now split them accordingly:
https://github.com/thde/rtorrent_exporter/commit/6542c7408cfd30804500b7ceb0c555103f8ef5d0

The tracker is not directly exposed by the API, therefore you'll need to do use this workaround.

**Comment by ac1dburnz** [comment]
I wish that would work for me :( but because of Sonarr and Radarr, I need things to be labelled differently then the name of 
the tracker. I see you're using label. Does it at all have Views instead? 
<img width="397" alt="Screenshot 2024-02-12 at 11 06 20 AM" src="https://github.com/thde/rtorrent_exporter/assets/10972668/49b4c8e7-2379-4505-b16d-fa29fc1a6f83">

**Comment by ac1dburnz** [comment]
Ah nvm i looked at the go code. However, Looks like there might be some light at the end of the tunnel 

https://github.com/mrobinsn/go-rtorrent/pull/21
